services:
  postgres:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - post_dw_vol:/var/lib/postgresql/data
      - ./sql:/opt/sql:ro
      - ./data:/opt/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  post_dw_vol: